stages:
  ingest:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - config.yaml
      - environment.yaml
    outs:
      - data/imdb_reviews.csv
  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
      - data/imdb_reviews.csv
      - src/data_preprocessing.py
      - params.yaml
    outs:
      - data/preprocessed_reviews.csv
  featurize:
    cmd: python src/feature_engineering.py
    deps:
      - data/preprocessed_reviews.csv
      - src/feature_engineering.py
      - params.yaml
    outs:
      - models/tfidf_vectorizer.pkl
      - data/features.npz
  train:
    cmd: python src/model_building.py
    deps:
      - data/features.npz
      - data/preprocessed_reviews.csv
      - src/model_building.py
      - params.yaml
    outs:
      - models/movie_review_model.pkl
  evaluate:
    cmd: python src/model_evaluation.py
    deps:
      - models/movie_review_model.pkl
      - models/tfidf_vectorizer.pkl
      - src/model_evaluation.py
    outs:
      - metrics/evaluation.txt
  register:
    cmd: python src/register_model.py
    deps:
      - models/movie_review_model.pkl
      - models/tfidf_vectorizer.pkl
      - src/register_model.py
