GCP_PROJECT=composite-age-451413-t4
REGION=us-central1
BUCKET_NAME=gs://imdb-bucket-test
DATA_PATH=data/imdb_reviews.csv
MODEL_PATH=models/movie_review_model.pkl
VECTORIZER_PATH=models/tfidf_vectorizer.pkl
GOOGLE_APPLICATION_CREDENTIALS=C:\Users\admin\Desktop\practise\imdb-test\Imdb-Review-Test-CG\composite-age-451413-t4-de540c15b70b.json
