name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[gcs]
          pip install mlflow

      - name: Run DVC Pipeline
        run: |
          dvc repro

      - name: Run MLFlow Tracking (Optional)
        run: |
          mlflow run . -P config=config.yaml

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy FASTAPI App with Uvicorn
        run: |
          pip install fastapi uvicorn
          nohup uvicorn flask_app.app:app --host 0.0.0.0 --port 8080 &
